package org.thewhitemage13.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity class representing an order in the system.
 * <p>
 * This class maps to the "orders" table in the database and contains all the details associated
 * with an order, including user ID, items, address, status, total sum, product ID, count of items,
 * method for easier logging and debugging.
 * </p>
 *
 * <h2>Key Features:</h2>
 * <ul>
 *     <li>Maps to the "orders" table in the database.</li>
 *     <li>Contains fields for user ID, items, address, status, total sum, product ID, count of items, and timestamps.</li>
 *     <li>Uses Lombok annotations for automatic generation of getters, setters, and constructors.</li>
 *     <li>Includes constructors for creating an order with or without the updated timestamp.</li>
 * </ul>
 *
 * <h2>Usage:</h2>
 * <p>
 * This class is used as a JPA entity to persist order data to the database. It is typically
 * used in service classes to represent and manipulate orders. The class can be easily
 * persisted using JPA repositories in a Spring-based application.
 * </p>
 *
 * @see jakarta.persistence.Entity
 * @see jakarta.persistence.Table
 * @see jakarta.persistence.Id
 * @see jakarta.persistence.GeneratedValue
 * @see jakarta.persistence.GenerationType
 * @see jakarta.persistence.Column
 * @see lombok.Getter
 * @see lombok.Setter
 *
 * @author Mukhammed Lolo
 * @version 1.0.0
 */
@Getter
@Setter
@Table(name = "orders")
@Entity
public class Order implements Serializable {

    /**
     * The unique identifier of the order.
     * This field is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The unique identifier of the user who placed the order.
     */
    @Column(name = "user_id")
    private Long userId;

    /**
     * The list of items in the order.
     */
    private String items;

    /**
     * The delivery address associated with the order.
     */
    private String address;

    /**
     * The current status of the order (e.g., "pending", "shipped", "delivered").
     */
    private String status;

    /**
     * The total sum of the order.
     */
    private BigDecimal totalSum;

    /**
     * The unique identifier of the product associated with the order.
     */
    @Column(name = "product_id")
    private Long productId;

    /**
     * The number of items of the product in the order.
     * This field cannot be {@code null}.
     */
    @Column(name = "count_of_items", nullable = false)
    private Long countOfItems;

    /**
     * The timestamp when the order was created.
     */
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    /**
     * The timestamp when the order was last updated.
     * This field can be {@code null} if not updated.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * Default constructor for {@link Order}.
     * Initializes a new order without setting the updated timestamp.
     */
    public Order() {
    }

    /**
     * Constructor for {@link Order} with all fields, including the updated timestamp.
     *
     * @param userId the ID of the user who placed the order
     * @param items the list of items in the order
     * @param address the delivery address for the order
     * @param status the status of the order
     * @param totalSum the total sum of the order
     * @param productId the product ID for the order
     * @param countOfItems the count of items in the order
     * @param createdAt the creation timestamp of the order
     * @param updatedAt the last updated timestamp of the order
     */
    public Order(Long userId, String items, String address, String status, BigDecimal totalSum, Long productId, Long countOfItems, LocalDateTime createdAt, LocalDateTime updatedAt) {
        this.userId = userId;
        this.items = items;
        this.address = address;
        this.status = status;
        this.totalSum = totalSum;
        this.productId = productId;
        this.countOfItems = countOfItems;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Constructor for {@link Order} without the updated timestamp.
     *
     * @param userId the ID of the user who placed the order
     * @param items the list of items in the order
     * @param address the delivery address for the order
     * @param status the status of the order
     * @param totalSum the total sum of the order
     * @param productId the product ID for the order
     * @param countOfItems the count of items in the order
     * @param createdAt the creation timestamp of the order
     */
    public Order(Long userId, String items, String address, String status, BigDecimal totalSum, Long productId, Long countOfItems, LocalDateTime createdAt) {
        this.userId = userId;
        this.items = items;
        this.address = address;
        this.status = status;
        this.totalSum = totalSum;
        this.productId = productId;
        this.countOfItems = countOfItems;
        this.createdAt = createdAt;
    }

    /**
     * Provides a string representation of the {@link Order}.
     * <p>
     * This method returns a string containing the values of {@code id}, {@code userId}, {@code items},
     * {@code address}, {@code status}, {@code totalSum}, {@code productId}, {@code countOfItems},
     * {@code createdAt}, and {@code updatedAt} for easier debugging and logging.
     * </p>
     *
     * @return a string representation of the {@link Order}
     */
    @Override
    public String toString() {
        return "Order{" +
                "id=" + id +
                ", userId=" + userId +
                ", items='" + items + '\'' +
                ", address='" + address + '\'' +
                ", status='" + status + '\'' +
                ", totalSum=" + totalSum +
                ", productId=" + productId +
                ", countOfItems=" + countOfItems +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                '}';
    }
}
